### ISSUE TITLE
EventException on place item in holder

### ISSUE THREAD

**Issue by SlimeDog** [PvPNiK/WeaponHolder#1]
Spigot 1.15.2
WeaponHolder 1.5

The world is enabled. The holder accepts the iron_hoe, but it is invisible. And this error in the log:
```
[09:56:41] [Server thread/ERROR]: Could not pass event HolderEquipItemEvent to WeaponHolder v1.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:541) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:528) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at me.pvpnik.weaponHolder.event.HolderCallEvent.holderAddItem(HolderCallEvent.java:185) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor486.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:541) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:528) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:442) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[?:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]  
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
        at org.bukkit.Location.add(Location.java:350) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        at me.pvpnik.weaponHolder.holder.Holder.spawn(Holder.java:43) ~[?:?]
        at me.pvpnik.weaponHolder.holder.HolderListener.onHolderEquipItem(HolderListener.java:38) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar-2020-03-01-2222:git-Spigot-8faa8b4-13ed05d]
        ... 27 more
```
The item can be recovered without error.

**Comment by SlimeDog** [comment]
Closed due to dev disinterest. We no longer use this plugin.
